#!/usr/bin/env tsx
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs'
import { join, basename, extname } from 'node:path'
import { optimize } from 'svgo'

import { INSTITUTIONS } from '../src/data/institutions'

const ASSETS_DIR = join(process.cwd(), 'assets', 'logos')
const LOGOS_OUT_DIR = join(process.cwd(), 'src', 'logos')
const LOGO_MAP_PATH = join(process.cwd(), 'src', 'data', 'logos.ts')

function readSvgs(): Map<string, string> {
  if (!existsSync(ASSETS_DIR)) return new Map()
  const map = new Map<string, string>()
  for (const file of readdirSync(ASSETS_DIR)) {
    if (extname(file).toLowerCase() !== '.svg') continue
    const slug = basename(file, '.svg')
    const raw = readFileSync(join(ASSETS_DIR, file), 'utf8')
    const optimized = optimize(raw, { multipass: true }).data
    map.set(slug, optimized)
  }
  return map
}

function buildLogoMap(svgsBySlug: Map<string, string>): Map<string, string> {
  const byCode = new Map<string, string>()
  for (const inst of INSTITUTIONS) {
    const svg = svgsBySlug.get(inst.slug)
    if (svg) byCode.set(inst.code, svg)
  }
  return byCode
}

function emitLogoMap(byCode: Map<string, string>) {
  const entries = [...byCode.entries()]
    .map(([code, svg]) => `  ${JSON.stringify(code)}: ${JSON.stringify(svg)},`)
    .join('\n')
  const body = `// AUTO-GENERATED by scripts/build-logos.ts. Do not edit.\nexport const LOGOS: Readonly<Record<string, string>> = {\n${entries}\n} as const\n`
  mkdirSync(join(process.cwd(), 'src', 'data'), { recursive: true })
  writeFileSync(LOGO_MAP_PATH, body, 'utf8')
}

function emitPerCodeEntries(byCode: Map<string, string>) {
  if (existsSync(LOGOS_OUT_DIR)) {
    rmSync(LOGOS_OUT_DIR, { recursive: true, force: true })
  }
  mkdirSync(LOGOS_OUT_DIR, { recursive: true })
  for (const [code, svg] of byCode) {
    const body = `// AUTO-GENERATED by scripts/build-logos.ts. Do not edit.\nconst svg = ${JSON.stringify(svg)}\nexport default svg\n`
    writeFileSync(join(LOGOS_OUT_DIR, `${code}.ts`), body, 'utf8')
  }
}

function main() {
  const svgs = readSvgs()
  const byCode = buildLogoMap(svgs)
  emitLogoMap(byCode)
  emitPerCodeEntries(byCode)
  console.log(`[build-logos] wrote ${byCode.size} logos`)
}

main()
