#!/usr/bin/env tsx
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs'
import { join, basename, extname } from 'node:path'
import { optimize } from 'svgo'

import { INSTITUTIONS } from '../src/data/institutions'

const VARIANTS = ['symbol', 'wordmark'] as const
type Variant = (typeof VARIANTS)[number]

const CWD = process.cwd()
const ASSETS_ROOT = join(CWD, 'assets', 'logos')
const SRC_LOGOS_ROOT = join(CWD, 'src', 'logos')
const LOGO_MAP_PATH = join(CWD, 'src', 'data', 'logos.ts')

// Ensure the SVG root has viewBox + preserveAspectRatio and drop pixel
// width/height so the parent container (CSS) controls sizing without
// distortion or clipping. Idempotent: skips attributes already present.
function normalizeRootAttrs(svg: string): string {
  return svg.replace(/<svg\b([^>]*)>/i, (_, attrs: string) => {
    let cleaned = attrs.replace(/\s(width|height)="(?!100%")[^"]*"/gi, '')
    if (!/preserveAspectRatio=/i.test(cleaned)) {
      cleaned += ' preserveAspectRatio="xMidYMid meet"'
    }
    return `<svg${cleaned}>`
  })
}

function readSvgsForVariant(variant: Variant): Map<string, string> {
  const dir = join(ASSETS_ROOT, variant)
  if (!existsSync(dir)) return new Map()
  const map = new Map<string, string>()
  for (const file of readdirSync(dir)) {
    if (extname(file).toLowerCase() !== '.svg') continue
    const slug = basename(file, '.svg')
    const raw = readFileSync(join(dir, file), 'utf8')
    const optimized = optimize(raw, {
      multipass: true,
      plugins: [
        {
          name: 'preset-default',
          params: {
            overrides: {
              // Keep viewBox; without it, container-based sizing breaks
              removeViewBox: false,
            },
          },
        },
        // Strip the fixed pixel width/height on the root element so
        // the container controls sizing.
        'removeDimensions',
      ],
    }).data
    map.set(slug, normalizeRootAttrs(optimized))
  }
  return map
}

function mapBySlugToByCode(bySlug: Map<string, string>): Map<string, string> {
  const byCode = new Map<string, string>()
  for (const inst of INSTITUTIONS) {
    const svg = bySlug.get(inst.slug)
    if (svg) byCode.set(inst.code, svg)
  }
  return byCode
}

function emitLogoMaps(byVariant: Record<Variant, Map<string, string>>) {
  const lines: string[] = ['// AUTO-GENERATED by scripts/build-logos.ts. Do not edit.', '']
  for (const variant of VARIANTS) {
    const map = byVariant[variant]
    const constName = variant === 'symbol' ? 'SYMBOL_LOGOS' : 'WORDMARK_LOGOS'
    const entries = [...map.entries()]
      .map(([code, svg]) => `  ${JSON.stringify(code)}: ${JSON.stringify(svg)},`)
      .join('\n')
    lines.push(`export const ${constName}: Readonly<Record<string, string>> = {`)
    lines.push(entries)
    lines.push('} as const')
    lines.push('')
  }
  mkdirSync(join(CWD, 'src', 'data'), { recursive: true })
  writeFileSync(LOGO_MAP_PATH, lines.join('\n'), 'utf8')
}

function emitPerCodeEntries(byVariant: Record<Variant, Map<string, string>>) {
  if (existsSync(SRC_LOGOS_ROOT)) {
    rmSync(SRC_LOGOS_ROOT, { recursive: true, force: true })
  }
  for (const variant of VARIANTS) {
    const outDir = join(SRC_LOGOS_ROOT, variant)
    mkdirSync(outDir, { recursive: true })
    for (const [code, svg] of byVariant[variant]) {
      const body = `// AUTO-GENERATED by scripts/build-logos.ts. Do not edit.\nconst svg = ${JSON.stringify(svg)}\nexport default svg\n`
      writeFileSync(join(outDir, `${code}.ts`), body, 'utf8')
    }
  }
}

function main() {
  const byVariant: Record<Variant, Map<string, string>> = {
    symbol: mapBySlugToByCode(readSvgsForVariant('symbol')),
    wordmark: mapBySlugToByCode(readSvgsForVariant('wordmark')),
  }
  emitLogoMaps(byVariant)
  emitPerCodeEntries(byVariant)
  console.log(
    `[build-logos] symbol=${byVariant.symbol.size} wordmark=${byVariant.wordmark.size}`,
  )
}

main()
